# Generated by Django 2.2.24 on 2021-11-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0002_billet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billet',
        ),
    ]
